#!/usr/bin/env bash
# =============================================================================
# setup_auditd.sh — one-time setup for kernel-level process resolution.
#
# Without this, the collector falls back to /proc scanning, which misses
# short-lived processes (touch/rm/cat). With it, every event resolves to a
# full pid/comm/user context with zero race condition.
#
# Usage:  sudo ./setup_auditd.sh
# =============================================================================

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "This script needs sudo for apt, systemctl, and sudoers setup."
    echo "Re-run as:  sudo ./setup_auditd.sh"
    exit 1
fi

# Only meaningful on Debian/Ubuntu-family systems with apt
if ! command -v apt-get > /dev/null; then
    echo "ERROR: apt-get not found — this script targets Debian/Ubuntu."
    exit 1
fi

echo "==> Installing auditd + audispd-plugins..."
apt-get update -qq
apt-get install -y -qq auditd audispd-plugins

echo "==> Starting auditd service..."
systemctl enable auditd --now

echo "==> Granting NOPASSWD auditctl/ausearch for user '${SUDO_USER:-$(logname 2>/dev/null || echo $USER)}'..."
PROJECT_USER="${SUDO_USER:-$(logname 2>/dev/null || echo $USER)}"
SUDOERS_FILE="/etc/sudoers.d/threat_detection_audit"

cat > "$SUDOERS_FILE" <<EOF
# Allows the threat-detection collector to manage audit rules without a password.
# Generated by setup_auditd.sh on $(date +%F)
$PROJECT_USER ALL=(root) NOPASSWD: /usr/sbin/auditctl, /usr/sbin/ausearch
EOF

chmod 440 "$SUDOERS_FILE"
visudo -c -f "$SUDOERS_FILE"  # validates syntax; aborts script on error

echo "==> Verifying auditd responds..."
auditctl -v > /dev/null && echo "    auditctl OK"
ausearch --start recent -m USER_LOGIN 2>/dev/null | head -1 > /dev/null && echo "    ausearch OK" || echo "    (ausearch returned no recent login events — fine, it works)"

echo
echo "✅ auditd setup complete."
echo "   The collector will now automatically use auditd on next start:"
echo "     ./run_all.sh            # rebuild + live smoke test with auditd"
echo "   or directly:"
echo "     source venv/bin/activate && python collector.py"
